- name : creating ec2 instances and r53 records
  hosts: local
  connection: local
  vars:
    ami_id: ami-0220d79f3f480ecf5
    sg_id: sg-0303a0e47aba592a6
    domain_name: daws-86.shop

  tasks:
    - name: create ec2 instances
      amazon.aws.ec2_instance:
        name: "{{ item }}"
        instance_type: "t3.micro"
        image_id: "{{ ami_id }}"
        security_group: "{{ sg_id }}"
        tags:
          Name: "{{ item }}"
      loop: "{{ instances }}"
      register: ec2_output
      
    - name: create route53 records
      amazon.aws.route53:
        state: present
        zone: "{{ domain_name }}"
        record: "{{ item.item }}-{{ env }}.{{ domain_name }}"
        ttl: 1
        type: A
        value: "{{ item.instances[0].private_ip_address }}"
        overwrite: true
      loop: "{{ ec2_output.results }}"

    - name: create route53 records
      amazon.aws.route53:
        state: present
        zone: "{{ domain_name }}"
        record: "{{ domain_name }}"
        ttl: 1
        type: A
        value: "{{ item.instances[0].public_ip_address }}"
        overwrite: true
      when: item.item  == "frontend"
      loop: "{{ ec2_output.results }}"

